server:
  port: 9411

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    addresses: 192.168.31.183:5672
    password: guest
    username: guest
    queue: zipkin

eureka:
  client:
    serviceUrl:
      defaultZone: http://movie:movie@localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#elasticsearch 仅支持2.x 到 5.x
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.31.183:5672
      password: guest
      username: guest
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://192.168.31.34:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1


