server:
  port: 8001

user:
  serviceUrl: http://localhost:8000/user/
  appId: microservice-simple-provider-user-trace-zipkin-stream

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: 192.168.31.183
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

# 配置日志级别，让sleuth打印 traceId
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEGUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://movie:movie@localhost:8761/eureka/
  instance:
    prefer-ip-address: true


