security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: movie                  # 配置登录的账号是user
    password: movie       # 配置登录的密码是password123
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://movie:movie@localhost:8761/eureka/




